project/views/auth.py
"""Routes Authentitation"""

from project.extensions import db

from flask import render_template, request, flash, redirect, session, url_for, g, abort, Blueprint
from sqlalchemy.exc import IntegrityError

from project.forms import UserAddForm, LoginForm, MessageForm, UserEditForm
from project.models import db, User, Message, Likes

# Create a Blueprint instance for the routes
auth_bp = Blueprint('auth', __name__, static_folder="static", template_folder="templates")

CURR_USER_KEY = "curr_user"
##############################################################################
# User signup/login/logout


@auth_bp.before_request
def add_user_to_g():
    """If we're logged in, add curr user to Flask global."""

    if CURR_USER_KEY in session:
        # g.user = User.query.get(session[CURR_USER_KEY])
        g.user = db.session.get(User, session[CURR_USER_KEY])


    else:
        g.user = None


def do_login(user):
    """Log in user."""

    session[CURR_USER_KEY] = user.id


def do_logout():
    """Logout user."""

    if CURR_USER_KEY in session:
        del session[CURR_USER_KEY]

@auth_bp.route('/signup', methods=["GET", "POST"])
def signup():
    """Handle user signup.

    Create new user and add to DB. Redirect to home page.

    If form not valid, present form.

    If the there already is a user with that username: flash message
    and re-present form.
    """
    form = UserAddForm()

    if form.validate_on_submit():
        try:
            user = User.signup(
                username=form.username.data,
                password=form.password.data,
                email=form.email.data,
                image_url=form.image_url.data or User.image_url.default.arg,
            )
            db.session.commit()

        except IntegrityError:
            flash("Username already taken", 'danger')
            return render_template('users/signup.html', form=form)

        do_login(user)

        return redirect("/")

    else:
        return render_template('users/signup.html', form=form)



@auth_bp.route('/login', methods=["GET", "POST"])
def login():
    """Handle user login."""

    form = LoginForm()

    if form.validate_on_submit():
        user = User.authenticate(form.username.data,
                                 form.password.data)

        if user:
            do_login(user)
            flash(f"Hello, {user.username}!", "success")
            return redirect(url_for('home.show_home'))

        flash("Invalid credentials.", 'danger')

    return render_template('users/login.html', form=form)


@auth_bp.route('/logout')
def logout():
    """Handle logout of user."""
    session.pop('curr_user')
    
    flash("Successfully Logged out", "success")
    return redirect(url_for('auth.login'))


@auth_bp.after_request
def add_header(req):
    """Add non-caching headers on every request."""

    req.headers["Cache-Control"] = "no-cache, no-store, must-revalidate"
    req.headers["Pragma"] = "no-cache"
    req.headers["Expires"] = "0"
    req.headers['Cache-Control'] = 'public, max-age=0'
    return req

project/views/message.py
"""Routes Messages"""

from project.extensions import db

from flask import render_template, request, flash, redirect, session, url_for, g, Blueprint
from project.forms import MessageForm
from project.models import db, User, Message

# Create a Blueprint instance for the routes
message_bp = Blueprint('message', __name__, static_folder="static", template_folder="templates")

CURR_USER_KEY = "curr_user"
##############################################################################
# User signup/login/logout


@message_bp.before_request
def add_user_to_g():
    """If we're logged in, add curr user to Flask global."""

    if CURR_USER_KEY in session:
        # g.user = User.query.get(session[CURR_USER_KEY])
        g.user = db.session.get(User, session[CURR_USER_KEY])


    else:
        g.user = None


def do_login(user):
    """Log in user."""

    session[CURR_USER_KEY] = user.id


def do_logout():
    """Logout user."""

    if CURR_USER_KEY in session:
        del session[CURR_USER_KEY]


##############################################################################
# Messages routes:

@message_bp.route('/new', methods=["GET", "POST"])
def add_message():
    """Add a message:

    Show form if GET. If valid, update message and redirect to user page.
    """

    if not g.user:
        flash("Access unauthorized.", "danger")
        return redirect("/")

    form = MessageForm()

    if form.validate_on_submit():
        msg = Message(text=form.text.data)
        g.user.messages.append(msg)
        db.session.commit()
        return redirect(f"/users/{g.user.id}")
    
    return render_template('messages/new.html', form=form)


@message_bp.route('/<int:message_id>', methods=["GET"])
def show_message(message_id):
    """Show a message."""

    msg = Message.query.get(message_id)
    return render_template('messages/show.html', message=msg)


@message_bp.route('/<int:message_id>/delete', methods=["POST"])
def delete_message(message_id):
    """Delete a message."""

    if not g.user:
        flash("Access unauthorized.", "danger")
        return redirect("/")

    msg = Message.query.get(message_id)
    db.session.delete(msg)
    db.session.commit()

    return redirect(f"/users/{g.user.id}")



@message_bp.after_request
def add_header(req):
    """Add non-caching headers on every request."""

    req.headers["Cache-Control"] = "no-cache, no-store, must-revalidate"
    req.headers["Pragma"] = "no-cache"
    req.headers["Expires"] = "0"
    req.headers['Cache-Control'] = 'public, max-age=0'
    return req

project/views/profile.py
"""Routes Profile"""

from project.extensions import db

from flask import render_template, request, flash, redirect, session, url_for, g, Blueprint
from project.forms import UserEditForm
from project.models import db, User, Message

# Create a Blueprint instance for the routes
profile_bp = Blueprint('profile', __name__, static_folder="static", template_folder="templates")

CURR_USER_KEY = "curr_user"
##############################################################################
# User signup/login/logout


@profile_bp.before_request
def add_user_to_g():
    """If we're logged in, add curr user to Flask global."""

    if CURR_USER_KEY in session:
        # g.user = User.query.get(session[CURR_USER_KEY])
        g.user = db.session.get(User, session[CURR_USER_KEY])


    else:
        g.user = None


def do_login(user):
    """Log in user."""

    session[CURR_USER_KEY] = user.id


def do_logout():
    """Logout user."""

    if CURR_USER_KEY in session:
        del session[CURR_USER_KEY]


##############################################################################
# General user routes:

@profile_bp.route('/')
def list_users():
    """Page with listing of users.

    Can take a 'q' param in querystring to search by that username.
    """

    search = request.args.get('q')

    if not search:
        users = User.query.all()
    else:
        users = User.query.filter(User.username.like(f"%{search}%")).all()

    return render_template('users/index.html', users=users)


@profile_bp.route('/<int:user_id>')
def show_user(user_id):
    """Show user profile."""

    user = User.query.get_or_404(user_id)

    # snagging messages in order from the database;
    # user.messages won't be in order by default
    messages = (Message
                .query
                .filter(Message.user_id == user_id)
                .order_by(Message.timestamp.desc())
                .limit(100)
                .all())


    return render_template('users/show.html', user=user, messages=messages)


@profile_bp.route('/<int:user_id>/following')
def show_following(user_id):
    """Show list of people this user is following."""

    if not g.user:
        flash("Access unauthorized.", "danger")
        return redirect("url_for('home.show_home')")

    user = User.query.get_or_404(user_id)
    return render_template('users/following.html', user=user)


@profile_bp.route('/<int:user_id>/followers')
def show_followers(user_id):
    """Show list of followers of this user."""

    if not g.user:
        flash("Access unauthorized.", "danger")
        return redirect("/")

    user = User.query.get_or_404(user_id)
    return render_template('users/followers.html', user=user)

@profile_bp.route('/<int:user_id>/likes')
def show_likes(user_id):
    """Show list of Likes of this User"""

    if not g.user:
        flash("Access unauthorized.", "danger")
        return redirect("/")
    
    user = User.query.get_or_404(user_id)
    liked_msg_ids = [msg.id for msg in user.likes]
    print('#############', liked_msg_ids)
    return render_template('users/likes.html', user=user)


@profile_bp.route('/follow/<int:follow_id>', methods=['POST'])
def add_follow(follow_id):
    """Add a follow for the currently-logged-in user."""

    if not g.user:
        flash("Access unauthorized.", "danger")
        return redirect("/")

    followed_user = User.query.get_or_404(follow_id)
    g.user.following.append(followed_user)
    db.session.commit()

    return redirect(f"/users/{g.user.id}/following")


@profile_bp.route('/stop-following/<int:follow_id>', methods=['POST'])
def stop_following(follow_id):
    """Have currently-logged-in-user stop following this user."""

    if not g.user:
        flash("Access unauthorized.", "danger")
        return redirect("/")

    followed_user = User.query.get(follow_id)
    g.user.following.remove(followed_user)
    db.session.commit()

    return redirect(f"/users/{g.user.id}/following")


@profile_bp.route('/profile', methods=["GET", "POST"])
def update_user():
    """Update profile for current user."""
    # user_id = session[CURR_USER_KEY]

    if not g.user:
        flash("Access unauthorized.", "danger")
        return redirect("/")
    
    user = g.user
    form = UserEditForm(obj=user)
    if form.validate_on_submit():
        if User.authenticate(user.username, form.password.data):
            user.username = form.username.data
            user.email = form.email.data
            user.location = form.location.data
            user.bio = form.bio.data
            user.image_url = form.image_url.data or "/static/images/default-pic.png"
            user.header_image_url = form.header_image_url.data or "/static/images/warbler-hero.jpg"
            
            db.session.commit()

            flash('Profile updated successfully!', 'success')
            return redirect(url_for('profile.show_user', user_id=user.id ))
        else:
            flash('Wrong Pasword or Username!', 'danger')
            
        return render_template('users/edit.html', form=form)
    
    return render_template('users/edit.html', form=form)


@profile_bp.route('/delete', methods=["POST"])
def delete_user():
    """Delete user."""

    if not g.user:
        flash("Access unauthorized.", "danger")
        return redirect("/")

    do_logout()

    db.session.delete(g.user)
    db.session.commit()

    return redirect("/signup")

@profile_bp.route('/add_like/<int:message_id>', methods=["GET", "POST"])
def add_like(message_id):
    """Toggle (Like or "Dislike") a Message from a User"""

    if not g.user:
        flash("Access unauthorized.", "danger")
        return redirect("/")
    
    liked_message = Message.query.get_or_404(message_id)
    if liked_message.user_id == g.user.id:
        return redirect("/")

    user_likes = g.user.likes
    if liked_message in user_likes:
        g.user.likes = [like for like in user_likes if like != liked_message]
    else:
        g.user.likes.append(liked_message)

    db.session.commit()
    return redirect("/")
       

@profile_bp.after_request
def add_header(req):
    """Add non-caching headers on every request."""

    req.headers["Cache-Control"] = "no-cache, no-store, must-revalidate"
    req.headers["Pragma"] = "no-cache"
    req.headers["Expires"] = "0"
    req.headers['Cache-Control'] = 'public, max-age=0'
    return req

project/templates/users/detail.html
{% extends 'base.html' %} {% block content %}

<div
  id="warbler-hero"
  class="jumbotron jumbotron-fluid"
  style="background-image: url('{{ user.header_image_url }}'); background-size: cover; background-position: center center;"
></div>

<img
  src="{{ user.image_url }}"
  alt="Image for {{ user.username }}"
  id="profile-avatar"
/>
<div class="row full-width">
  <div class="container">
    <div class="row justify-content-end">
      <div class="col-9">
        <ul class="user-stats nav nav-pills">
          <li class="stat">
            <p class="small">Messages</p>
            <h4>
              <a href="{{url_for('profile.show_user', user_id=user.id)}}"
                >{{ user.messages | length }}</a
              >
            </h4>
          </li>
          <li class="stat">
            <p class="small">Following</p>
            <h4>
              <a href="{{url_for('profile.show_following', user_id=user.id)}}"
                >{{ user.following | length }}</a
              >
            </h4>
          </li>
          <li class="stat">
            <p class="small">Followers</p>
            <h4>
              <a href="{{url_for('profile.show_followers', user_id=user.id)}}"
                >{{ user.followers | length }}</a
              >
            </h4>
          </li>
          <li class="stat">
            <p class="small">Likes</p>
            <h4>
              <!-- <a href="/users/{{user.id}}/likes">{{ user.likes | length }}</a> -->
              <a href="{{url_for('profile.show_likes', user_id=user.id)}}"
                >{{ user.likes | length }}</a
              >
            </h4>
          </li>
          <div class="ml-auto">
            {% if g.user.id == user.id %}
            <a
              href="{{ url_for('profile.update_user')}}"
              class="btn btn-outline-secondary"
              >Edit Profile</a
            >
            <form
              method="POST"
              action="{{ url_for('profile.delete_user' )}}"
              class="form-inline"
            >
              <button class="btn btn-outline-danger ml-2">
                Delete Profile
              </button>
            </form>
            {% elif g.user %} {% if g.user.is_following(user) %}
            <form
              method="POST"
              action="{{ url_for('profile.stop_following', follow_id=user.id) }}"
            >
              <button class="btn btn-primary">Unfollow</button>
            </form>
            {% else %}
            <form
              method="POST"
              action="{{ url_for('profile.add_follow', follow_id=user.id) }}"
            >
              <button class="btn btn-outline-primary">Follow</button>
            </form>
            {% endif %} {% endif %}
          </div>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-3">
    <h4 id="sidebar-username">@{{ user.username }}</h4>
    <p>{{user.bio}}</p>
    <p class="user-location">
      <span class="fa fa-map-marker"></span>{{user.location}}
    </p>
  </div>

  {% block user_details %} {% endblock %}
</div>

{% endblock %}

project/templates/users/edit.html
{% extends 'base.html' %} {% block content %}

<div class="row justify-content-md-center">
  <div class="col-md-4">
    <h2 class="join-message">Edit Your Profile.</h2>
    <form method="POST" id="user_form">
      {{ form.hidden_tag() }} {% for field in form if field.widget.input_type !=
      'hidden' and field.name != 'password' %}
      {{field.label(class="form-label")}} {% for error in field.errors %}
      <span class="text-danger">{{ error }}</span>
      {% endfor %} {{ field(class="form-control") }} {% endfor %}

      <p>Enter your password to Save:</p>
      {% if form.password.errors %} {% for error in form.password.errors %}
      <span class="text-danger"> {{ error }} </span>
      {% endfor %} {% endif %} {{ form.password( class="form-control") }}

      <div class="edit-btn-area">
        <button class="btn btn-success">Edit this user!</button>
        <a
          href="{{url_for('profile.show_user', user_id=g.user.id)}}"
          class="btn btn-outline-secondary"
          >Cancel</a
        >
      </div>
    </form>
  </div>
</div>

{% endblock %}

project/templates/users/followers.html
{% extends 'users/detail.html' %}

{% block user_details %}
  <div class="col-sm-9">
    <div class="row">

      {% for follower in user.followers %}

        <div class="col-lg-4 col-md-6 col-12">
          <div class="card user-card">
            <div class="card-inner">
              <div class="image-wrapper">
                <img src="{{ follower.header_image_url }}" alt="" class="card-hero">
              </div>
              <div class="card-contents">
                <a href="{{url_for('profile', follower_id=follower.id)}}" class="card-link">
                  <img src="{{ follower.image_url }}" alt="Image for {{ follower.username }}" class="card-image">
                  <p>@{{ follower.username }}</p>
                </a>

                {% if g.user.is_following(follower) %}
                  <form method="POST"
                        action="{{url_for('profile.stop_following', follower_id=follower.id)}}">
                    <button class="btn btn-primary btn-sm">Unfollow</button>
                  </form>
                {% else %}
                  <form method="POST" action="{{url_for('profile.add_follow', follower_id=follower.id)}}">
                    <button class="btn btn-outline-primary btn-sm">Follow</button>
                  </form>
                {% endif %}

              </div>
              <p class="card-bio">{{follower.bio}}</p>
            </div>
          </div>
        </div>

      {% endfor %}

    </div>
  </div>

{% endblock %}

project/templates/users/following.html
{% extends 'users/detail.html' %}
{% block user_details %}
  <div class="col-sm-9">
    <div class="row">

      {% for followed_user in user.following %}

        <div class="col-lg-4 col-md-6 col-12">
          <div class="card user-card">
            <div class="card-inner">
              <div class="image-wrapper">
                <img src="{{ followed_user.header_image_url }}" alt="" class="card-hero">
              </div>
              <div class="card-contents">
                <a href="{{url_for('profile.show_user', user_id=followed_user.id)}}" class="card-link">
                  <img src="{{ followed_user.image_url }}" alt="Image for {{ followed_user.username }}" class="card-image">
                  <p>@{{ followed_user.username }}</p>
                </a>
                {% if g.user.is_following(followed_user) %}
                  <form method="POST"
                        action="{{url_for('profile.stop_following', follow_id=followed_user.id)}}">
                    <button class="btn btn-primary btn-sm">Unfollow</button>
                  </form>
                {% else %}
                  <form method="POST" action="{{url_for('profile.add_follow', follow_id=followed_user.id)}}">
                    <button class="btn btn-outline-primary btn-sm">Follow</button>
                  </form>
                {% endif %}

              </div>
              <p class="card-bio">{{followed_user.bio}}</p>
            </div>
          </div>
        </div>

      {% endfor %}

    </div>
  </div>
{% endblock %}

project/templates/users/index.html
{% extends 'base.html' %}
{% block content %}
  {% if users|length == 0 %}
    <h3>Sorry, no users found</h3>
  {% else %}
    <div class="row justify-content-end">
      <div class="col-sm-9">
        <div class="row">

          {% for user in users %}

            <div class="col-lg-4 col-md-6 col-12">
              <div class="card user-card">
                <div class="card-inner">
                  <div class="image-wrapper">
                    <img src="{{ user.header_image_url }}" alt="" class="card-hero">
                  </div>
                  <div class="card-contents">
                    <a href="{{url_for('profile.show_user', user_id=user.id)}}" class="card-link">
                      <img src="{{ user.image_url }}" alt="Image for {{ user.username }}" class="card-image">
                      <p>@{{ user.username }}</p>
                    </a>

                    {% if g.user %}
                      {% if g.user.is_following(user) %}
                        <form method="POST"
                              action="{{url_for('profile.stop_following', follow_id=user.id)}}">
                          <button class="btn btn-primary btn-sm">Unfollow</button>
                        </form>
                      {% else %}
                        <form method="POST"
                              action="{{url_for('profile.add_follow', follow_id=user.id)}}">
                          <button class="btn btn-outline-primary btn-sm">Follow</button>
                        </form>
                      {% endif %}
                    {% endif %}

                  </div>
                  <p class="card-bio">{{user.bio}}</p>
                </div>
              </div>
            </div>

          {% endfor %}

        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

project/templates/users/likes.html
{% extends 'users/detail.html' %}

{% block user_details %}
        <div class="col-sm-6">
            <ul class="list-group" id="messages">
                {% for msg in user.likes %}
                <li class="list-group-item">
                  <a href="{{ url_for('message.show_message', message_id=msg.id) }}" class="message-link">
                  </a>
                  <a href="{{ url_for('profile.show_user', user_id=msg.user_id) }}">
                    <img src="{{msg.user.image_url}}" alt="user image" class="timeline-image">
                  </a>
        
                  <div class="message-area">
                    <a href="{{ url_for('profile.show_user', user_id=msg.user_id) }}">@{{msg.user.username}}</a>
                    <span class="text-muted">{{ msg.timestamp.strftime('%d %B %Y') }}
                    </span>
                    <p>{{msg.text}}</p>
                  </div>
                </li>
                {% endfor %}
            </ul>
          </div>
        </div>
    

{% endblock %}

project/templates/users/login.html
{% extends 'base.html' %}

{% block body_class %}onboarding{% endblock %}

{% block content %}

  <div class="row justify-content-md-center">
    <div class="col-md-7 col-lg-5">
      <h2 class="join-message">Welcome back.</h2>
      <p class="description">
        Login for Warbler. Don't have an Account ? <a href="{{url_for('auth.signup')}}">Register here!</a>
      </p>

      <form method="POST" id="user_form" autocomplete="off">
        {{ form.hidden_tag() }}

        {% for field in form if field.widget.input_type != 'hidden' %}
          {% for error in field.errors %}
            <span class="text-danger">{{ error }}</span>
          {% endfor %}
          {{ field(placeholder=field.label.text, class="form-control") }}
        {% endfor %}

        <button class="btn btn-primary btn-block btn-lg">Log in</button>
      </form>
    </div>
  </div>

{% endblock %}

project/templates/users/show.html
{% extends 'users/detail.html' %}
{% block user_details %}
  <div class="col-sm-6">
    <ul class="list-group" id="messages">

      {% for message in messages %}

        <li class="list-group-item">
          <a href="{{ url_for('message.show_message', message_id=message.id) }}" class="message-link"/>

          <a href="/users/{{ user.id }}">
          <a href="{{ url_for('profile.show_user', user_id=user.id) }}">
            <img src="{{ user.image_url }}" alt="user image" class="timeline-image">
          </a>

          <div class="message-area">
            <a href="{{ url_for('profile.show_user', user_id=user.id) }}">@{{ user.username }}</a>
            <span class="text-muted">{{ message.timestamp.strftime('%d %B %Y') }}</span>
            <p>{{ message.text }}</p>
          </div>
        </li>

      {% endfor %}

    </ul>
  </div>
{% endblock %}

project/templates/users/signup.html
{% extends 'base.html' %}

{% block body_class %}onboarding{% endblock %}

{% block content %}

  <div class="row justify-content-md-center">
  <div class="col-md-7 col-lg-5">
    <h2 class="join-message">Join Warbler today.</h2>
    <form method="POST" id="user_form">
      {{ form.hidden_tag() }}

      {% for field in form if field.widget.input_type != 'hidden' %}
        {% for error in field.errors %}
          <span class="text-danger">{{ error }}</span>
        {% endfor %}
        {{ field(placeholder=field.label.text, class="form-control") }}
      {% endfor %}

      <button class="btn btn-primary btn-lg btn-block">Sign me up!</button>
    </form>
  </div>
</div>

{% endblock %}